apiVersion: apps/v1
kind: Deployment
metadata:
  name: devworkspace-client-deployment
  namespace: devworkspace-controller
  labels:
    app: devworkspace-client
    app.kubernetes.io/name: dashboard-backend
    app.kubernetes.io/part-of: dashboard-backend
spec:
  selector:
    matchLabels:
      app: devworkspace-client
  template:
    metadata:
      labels:
        app: devworkspace-client
    spec:
      containers:
      - name: devworkspace-client
        image: quay.io/jpinkney/devworkspace-client
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      serviceAccountName: dashboard-backend
